### ISSUE TITLE
Error On Startup

### ISSUE THREAD

**Issue by SequaciousGAMES** [freddedotme/BuildSubmission#1]
Getting this error on startup

`[06:43:52] [Server thread/ERROR]: Error occurred while enabling BuildSubmission v4.2 (Is it up to date?)
java.lang.NullPointerException
	at me.fredde.BuildSubmission.Builder.writeLocation(Builder.java:52) ~[?:?]
	at me.fredde.BuildSubmission.Builder.<init>(Builder.java:21) ~[?:?]
	at me.fredde.BuildSubmission.Main.fetchBuilders(Main.java:123) ~[?:?]
	at me.fredde.BuildSubmission.Main.onEnable(Main.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.jar:git-Spigot-3fb9445-fbb47e8]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

Plugin still seems to enable, doin /bs <anything> just shows the commands list

**Comment by freddedotme** [comment]
Hey mate, I’ll look into it as soon as possible.

**Comment by freddedotme** [comment]
So the reason seem to be that there is an issue that it tries to fetch a file that can't be found. I'm quite sure it's the builders.yml. Is the plugin working as usual otherwise? Does it create the necessary files?

**Comment by SequaciousGAMES** [comment]
It doesn't appear to be creating the builders.yml on clean startup, but I already have one from a while ago

**Comment by freddedotme** [comment]
What happens if you temporarily start it with a clean startup and then submit a build in game? Does it create the file then?
